### ISSUE TITLE
npm package?

### ISSUE THREAD

**Issue by j-5-s** [mhsdesign/jit-browser-tailwindcss#1]
This is a really cool project, are you gonna make it an npm package?

**Comment by mhsdesign** [comment]
thanks, yes sure im gonna do that, im not happy how this is distributed currently.

how would you use / install this package?

-----

i think its not possible to import this package from source in a custom js app like this `src/main.js`, as the custom webpack wont apply then i think. But then when using `dist/main.js`, there is only a function exposed manually on the global window, what doesnt seem right.

As of right now fx this wont work in the browser as there is no export via webpack:
```
const tailwind = import('./dist/main.js');
```

and webpack es6 modules are still an experiment puh and so on - many questions.

Should one better use rollup so one can import from the bundeled js file? Maybe treeshaking works too then?

- i feel like i need to find answers first to some of the questions, to have a nice public api - and then publish it ^^

**Comment by j-5-s** [comment]
yeah, i think you're right. i wouldn't want it in my build and would have to do something like a dynamic import. That said, having it on a public cdn would make it easy to just add the script tag and continue using it the way you originally published it. For now i've just copied the dist into my public folder and am pointing a script tag at it.

**Comment by mhsdesign** [comment]
so ideally would be if one could use this package like:

### Usecase 1 / Import
(in <script type="module"> and in a bundle and tell the bundler that this export is external)
```
import dynamicTailwind from './dist/main.js'
```

### Usecase 2 / Dynamic import
(in any <script> or in a bundeled app)
```
const dynamicTailwind = import('./dist/main.js');
```

### Usecase 3 / Oldscool
(in any <script> or in a bundeled app - that is loaded after this script tag: `<script src="./dist/main.js"></script>`)
```
const dynamicTailwind = window.browserJitGenerateTailwindcss
```

----

and i agree on the cdn stuff, that is much more comfortable, but i would also like to have a local hosting solution - i could imagine creating a dummy package which imports from the `node_modules/dynamicTailwind/dist/main.js` and exposes it. Or use some codesplitting etc ...


----

i tried to archive the above with webpack 4 but im stuck so currently only Usecase 3 works

**Comment by mhsdesign** [comment]
hu just found this package: maybe we can learn something from https://github.com/mapgrid/tailwindcss-browser, outdated and no jit, but still there is a webpack config (git log) and a rollup config ...

**Comment by j-5-s** [comment]
i tried playing around with rollup as its looks like a good idea, but ran into a lot of the stuff you had already stubbed out. Rather than fighting it i just went back to using webpack with the above pr.

**Comment by mhsdesign** [comment]
how far did you get with rollup? maybe i can give it another shot?

**Comment by j-5-s** [comment]
Not far at all. Give it a shot if you have time. I'm focused on a few other things at the moment. Thanks!

**Comment by mhsdesign** [comment]
https://github.com/mhsdesign/browser-jit-generate-tailwindcss/issues/1#issuecomment-1063955960

2 and 3 work, but only in a custom bundle - otherwise one needs to use it like:

```js
await import('../dist/main.js')
console.log(window.browserJitGenerateTailwindcss)
```

**Comment by mhsdesign** [comment]
voila https://www.npmjs.com/package/@mhsdesign/jit-browser-tailwindcss

**Comment by j-5-s** [comment]
Awesome, thanks!

**Comment by mhsdesign** [comment]
btw @jamescharlesworth i just did a full rewrite xD With esbuild as bundler, and completely different internals, webworker, and half of bundle size: 250kb
https://github.com/mhsdesign/jit-browser-tailwindcss/commit/48847787122cb6f55eea9798d2fcfcd75da56a0b

**Comment by j-5-s** [comment]
thanks @mhsdesign thats awesome and I appreciate you letting me know! I've been meaning to look at esbuild for a different project. Your commit will definitely help guide me in some changes.  Thanks again!

**Comment by mhsdesign** [comment]
Hi @jamescharlesworth now v0.2.0 is fully done ;)
Can you maybe check if it still works for your projekt? ^^ (in combination with webpack)

(esbuild is crazy good ^^)
