### ISSUE TITLE
Does it work with @apply and stylesheets?

### ISSUE THREAD

**Issue by merijnponzo** [mhsdesign/jit-browser-tailwindcss#11]
Great Work!

I was thinking about some tailwind wordpress integrations with server sided options as well..
I added a style.css and imported this within the jit-browser-tailwindcss api

Input
```
.theme-header{ @apply sticky top-0; }
```
Output
```
.sticky { position: sticky } .top-0 { top: 0px } 
```

It is extracting the right classes, but it's not respecting the nested classes

I import the cdn file (locally) and import the tailwind.config.js as well (this is [exported](https://github.com/tailwindlabs/tailwindcss/discussions/5858) as a module and seems to work)

```
  await import('<?php echo $tailwind_parser; ?>');
            // import config 
            const config = await import('<?php echo $config; ?>');

            delete config.default.content;
           
            // get css
            const content = document.getElementById('tailwind_input').innerHTML;
            // create config
            const tailwind = window.createTailwindcss({
                tailwindConfig: config.default,
            })
            // 
            const css = await tailwind.generateStylesFromContent(`
                @tailwind components;
                @tailwind utilities;
         `, [content])

```
Am i missing something or is this not supported?

thanks

**Comment by merijnponzo** [comment]
i think now it's working
Were ${content} is the stylesheet contents with @tailwind-base and classes 

```
   // 
            const css = await tailwind.generateStylesFromContent(`
               ${content}
         `, [])

```

Super!

**Comment by mhsdesign** [comment]
Glad to hear it is working, so we can close this?

**Comment by merijnponzo** [comment]
yes, thanks
