### ISSUE TITLE
Support for Tailwind CSS v3.4

### ISSUE THREAD

**Issue by ErwinAI** [mhsdesign/jit-browser-tailwindcss#16]
I've been investigating how to support v3.4. Thus far, I figured out that the 'build' script for tailwindcss contains a new global var for determining if Oxide is used (`--config jsc.transform.optimizer.globals.vars.__OXIDE__='"false"'`). However, when running any example, an error is thrown:

```
Uncaught (in promise) ReferenceError: __OXIDE__ is not defined
    at get disableColorOpacityUtilitiesByDefault [as disableColorOpacityUtilitiesByDefault] (tailwindcss.worker.js:29:72755)
```

Suppose we can fix this (tried hardcoding this to 'false') causes a new error that I think is unrelated:

```
Uncaught (in promise) CssSyntaxError: <css input>:1:1: Unknown word
    at Ue.error (tailwindcss.worker.js:18:6321)
```

I'm not entirely sure how to effectively debug and progress on these issues.

**Comment by mhsdesign** [comment]
Fixed via https://github.com/mhsdesign/jit-browser-tailwindcss/releases/tag/0.4.0
