### ISSUE TITLE
Support for Tailwind CSS v3.2.1

### ISSUE THREAD

**Issue by ErwinAI** [mhsdesign/jit-browser-tailwindcss#7]
Hello @mhsdesign ,

First of all, thank you for making this package. A while ago, I built something similar for my use-case, only to find you did it way better 😂

I'm trying to generate classes with the fancy new variants from Tailwind version 3.2.1 such as `aria-checked:bg-gray-100`, `min-[712px]:bg-gray-100` and `max-lg:p-8`. The package.json says `^3.0.0` but I can't seem to override it. Can the dependencies be updated perhaps?

Already tried this in my package.json but no luck.
```
"overrides": {
    "@mhsdesign/jit-browser-tailwindcss": {
      "tailwindcss": "3.2.1"
    }
  }
```

**Comment by mhsdesign** [comment]
Hi cool that you like it ;)

yes it is not as easy as you thought. Tailwindcss is prepacked with this package, so that the end-user doesnt need to worry about a complex build process.

I would need to publish a new version with Tailwind v3.2.1 ;)
So version `0.2.2` will contain Tailwind v3.2.1


Are you currently using esbuild yourself by any chance?
And which `@mhsdesign/jit-browser-tailwindcss` version are you on?

**Comment by ErwinAI** [comment]
I'm building tailwind.worker.js (with esbuild) in a separate project and using it as a static asset in my main project where I use a web worker. It's already using the latest version (0.2.1) right now.

**Comment by mhsdesign** [comment]
voila https://github.com/mhsdesign/jit-browser-tailwindcss/releases/tag/0.2.2

maybe we need a way to build this package dynamically and not once per release ...

**Comment by ErwinAI** [comment]
@mhsdesign Thank you!

Yes, that might be best, otherwise, that's at least 2-3 updates a year to keep up with new Tailwind versions alone.
I'm not sure how to do that though..

**Comment by merijnponzo** [comment]
Hi there!
So i tried to prepack with tailwind 3.3 since it has this amazing line-clamp function.
It is building the esm modules but i need the cdn file as well, but that one is failing.

i tried to add 
```
"prepack": "node build.js --external @tailwindcss/oxide",
```
within my package.json but that doesn't work.
Any idea, how and if the jit-browser-tailwindcss can be updated to 3.3?


```
✘ [ERROR] Could not resolve "@tailwindcss/oxide"

    node_modules/tailwindcss/src/lib/expandTailwindAtRules.js:135:36:
      135 │ ...candidate of require('@tailwindcss/oxide').parseCandidateStrin...
          ╵                         ~~~~~~~~~~~~~~~~~~~~

  You can mark the path "@tailwindcss/oxide" as external to exclude it from the
  bundle, which will remove this error. You can also surround this "require"
  call with a try/catch block to handle this failure at run-time instead of
  bundle-time.


  dist/module.esm.js      280.2kb
  dist/module.esm.js.map  532.9kb

```

**Comment by ErwinAI** [comment]
@merijnponzo This module already uses Tailwind CSS v3.3 (see [package.json#44](https://github.com/mhsdesign/jit-browser-tailwindcss/blob/main/package.json#L44))

The problem seems to be that you are trying to use @tailwindcss/oxide. How come? Currently, Oxide is not part of the stable latest version of Tailwind CSS.

**Comment by merijnponzo** [comment]
thanks ErwinAi, i didn't add @tailwindcss/oxide first but what i did was copying
https://github.com/mhsdesign/jit-browser-tailwindcss/releases/tag/0.2.2
this package.json and change the tailwind to 3.3, then i run into this error.

I copied you package.json and thats working.
thanks!

**Comment by merijnponzo** [comment]
so i ran 'yarn prepack' to build cdn.min.js which works succesfully with your release/tag/0.2.2
i changed my previous cdn.min.js (tailwind 3.1) with the new one (3.3)

within my app.js:
```
const tailwindCss = require("./cdn.min.js");
  const tailwind = await window.createTailwindcss({
    tailwindConfig: configFile,
  });
```
My previous verions of cdn.min.js gave no errors but now i got a new error within my app.js 
```
Uncaught (in promise) ReferenceError: __OXIDE__ is not defined
```
however, i could try to load the jit-browser-tailwindcss as a module.esm.js
