### ISSUE TITLE
Can't start examples

### ISSUE THREAD

**Issue by rborn** [mhsdesign/jit-browser-tailwindcss#8]
👋 this looks super nice, but I don't seem to be able to start any of the examples.

`rm -rf ./dist && node build.js
✘ [ERROR] Could not resolve "jit-browser-tailwindcss"
`

any idea? 🙏

**Comment by mhsdesign** [comment]
thanks ;)

yes i think you need to prepack first ;) Fyi im using npm workspaces so it should work this way:

```sh
git clone git@github.com:mhsdesign/jit-browser-tailwindcss.git
cd jit-browser-tailwindcss

npm install
npm run prepack # so you have the dist files like installed from npm
npm --workspace esbuild-demo start
```

**Comment by rborn** [comment]
Thanks for replying 🙏

I was using `yarn`  however it seems that there are some scripts missing, like `start` in the workspace

**Comment by mhsdesign** [comment]
yes i didnt setup yarn workspaces - so you might need to do thinks a little different ;) or use npm. Or cd into the examples and install this lib via npm as if it were the projekt root.

**Comment by rborn** [comment]
Sorry, I meant even with npm to worn't start :)

**Comment by mhsdesign** [comment]
upsi youre right indeed i may have been a bit `sloppy`

there is only a `build` script

feel free to open a pr ;)

otherwise ill fix it some time
